version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres_server
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: admin
    ports:
      - "5432:5432"                
    volumes: 
      - ./postgres-conf:/var/lib/postgresql/data      

  mysql:
    image: mysql:latest
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - ./mysql_data:/var/lib/mysql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin987"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql_data:/var/opt/mssql

  oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle_server
    ports:
      - "1521:1521"     
    environment:
      ORACLE_SID: oracle	
      ORACLE_PWD: "Admin987"
    volumes:
      - ./oracle_data:/opt/oracle/oradata

networks:
  postgres:
    name: postgres
    driver: bridge
volumes:
  postgres-conf:
    driver: local
  mysql_data:
    driver: local