version: "3"
services:
  postgres:
    build:
      context: ./Dockerfiles/postgres
    user: "user:user"
    networks:
      - postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
    ports:
      - "5432:5432"                
    volumes: 
      - ./postgres-conf:/var/lib/postgresql/data      

networks:
  postgres:
    name: postgres
    driver: bridge
