version: '3.7'

services:
  mssql:
    build:
      context: ./Dockerfiles/sql_server
    container_name: sql_server
    user: "user:user"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "admin"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql_data:/var/opt/mssql     
