version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "transaction_isolation"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local