version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin987"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql_data:/var/opt/mssql
    #sudo chown 10001:10001 ./mssql_data