version: '3.7'

services:
  mysql:
    build:
      context: ./Dockerfiles/mysql
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "MySQL123"
    volumes:
      - ./mysql_data:/var/lib/mysql
