version: '3.7'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle_server
    ports:
      - "1521:1521"
    environment:
      ORACLE_SID: oracle
      ORACLE_PWD: "Admin987"
    volumes:
      - ./oracle_data:/opt/oracle/oradata
    #sudo chown -R 54321:54321 oracle_data/